nestjs:
  replicaCount: 1
  image: 
    repository: leanespind92/desafio11
    tag: latest
    pullPolicy: IfNotPresent
  service: 
    type: ClusterIP
    port: 3000 

mongodb:
  replicaCount: 1
  image: 
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017

ingress:
  enabled: false
  name: ""
  nginxClass: ""
  path: /
  pathType: ImplementationSpecific
  host: ""
  tls: []
  extraHosts: []
  extraPaths: []