# Configuraci贸n de la aplicaci贸n NestJS
nestjs:
  replicaCount: 1
  image: 
    repository: leanespind92/desafio11
    tag: latest
    pullPolicy: IfNotPresent
  service: 
    type: ClusterIP
    port: 3000 

# Configuraci贸n de MongoDB
mongodb:
  replicaCount: 1
  image: 
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017

# Configuraci贸n de Ingress
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: "example.com"
      paths:
        - path: /
          pathType: Prefix
          port: 80
  tls:
    - hosts:
        - "example.com"
      secretName: "example-tls"
