apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: {{ .Values.mongodb.replicaCount }}  # Cantidad de réplicas configurada en los valores
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}  # Imágenes de MongoDB
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.dbUser }}  # Usuario de la base de datos
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.dbPassword }}  # Contraseña de la base de datos
        command: ["mongod", "--replSet", "rs0"]  # Iniciar MongoDB como un replica set
